#!/bin/bash

# user-service
export USER_SERVICE_SERVER_PORT=6000
export USER_SERVICE_SERVLET_CONTEXT_PATH=/user-service
export USER_DB_URL=jdbc:postgresql://user-db:5432/postgres
export USER_DB_USERNAME=postgres
export USER_DB_PASSWORD=password
export USER_SERVICE_KAFKA_BINDER="kafka"
export USER_SERVICE_KAFKA_DESTINATION="user"
export USER_SERVICE_KAFKA_CONTENTTYPE="application/json"
export USER_SERVICE_KAFKA_GROUP="user-group"
export USER_SERVICE_KAFKA_PRODUCER_REQUIREDGROUPS="user-group"
export USER_SERVICE_KAFKA_BROKERS=kafka
export USER_SERVICE_KAFKA_DEFAULT_BROKER_PORT=29092
export USER_SERVICE_KAFKA_DEFAULT_ZK_PORT=32181

# globals
export TOKEN_EXPIRATION=604800
export TOKEN_SECRET=IUJSJWMveG5bdjNBdjk7cg==
export IMAGES_DIRECTORY_PATH=/app/images/
export SPRING_PROFILES_ACTIVE=local
export SPRING_JPA_SHOW_SQL=true
export SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS=false
export SWAGGER_HOST=10.10.15.46:8080
export SPRING_MAIL_HOST="smtp.gmail.com"
export SPRING_MAIL_PORT=587
export SPRING_MAIL_USERNAME="a.music.platform@gmail.com"
export SPRING_MAIL_PASSWORD="project-a-music"
export SPRING_MAIL_PROTOCOL="smtp"
export SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
export SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED=true
export ACTIVATING_URI="http://10.10.15.46:8080/user-service/verification/email/check-email-code/"
export SPRING_SECURITY_OAUTH2_SUCCESSURI="/auth/get-token/"
export SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_ID=1206632243037683
export SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_SECRET="d413cdcc59f4c420dbdae2f8a73c2069"
export SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID="430712594411-0gkc60m97vtgp37icmell301mq2ahqgd.apps.googleusercontent.com"
export SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET="F1n7XvRHwA-o87Gw3YOhLLvr"
export SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID="c8d99412d21bc7c817ef"
export SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET="a6520cc497ee555d40b568e4b9c9153fb9c3cdad"
export PAYPAL_CLIENT_ID="AXs8My4DQDuf6DVz23uYEJxggWvcWBDXIoqcsmvP6v9h6-z7RUEAWFyr9fzu1pEXA46f5dXmtX0_3Ayo"
export PAYPAL_CLIENT_SECRET="ECKixR15yHZ-03mC_TV9aIPHAJgBU9c8MeXsycXCucCYxZWIKaM800B-mEFZh4PxxyIfOUbCxsQmp7Sd"
export PAYPAL_MODE="live"
export SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE="50MB"
export SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE="50MB"
export SUBSCRIPTION_URI="http://10.10.15.46:8080/user-service/user-subscriptions/check-email-code/"

docker-compose up --build -d
