INSERT INTO countries (country_name)
values ('Russia'),
       ('Ukraine'),
       ('Belarus'),
       ('Kazakhstan'),
       ('United States'),
       ('Great Britain'),
       ('Italy'),
       ('Germany'),
       ('Czech Republic'),
       ('Spain'),
       ('Portugal'),
       ('Armenia'),
       ('Azerbaijan'),
       ('Denmark'),
       ('Norway'),
       ('Finland'),
       ('Turkey'),
       ('Egypt'),
       ('India'),
       ('China'),
       ('Switzerland'),
       ('Japan'),
       ('Brazil'),
       ('Mexico'),
       ('Canada'),
       ('South Korea'),
       ('Netherlands'),
       ('Sweden'),
       ('Israel'),
       ('Poland')
       ;