INSERT INTO cities (city_name, country_id)
values ('Moscow', 1),
       ('Saints-Petersburg', 1),
       ('Yekaterinburg', 1),
       ('Kiev', 2),
       ('Odesa', 2),
       ('Kharkiv', 2),
       ('Minsk', 3),
       ('Vitebsk', 3),
       ('Gomel', 3),
       ('Almaty', 4),
       ('Shymkent', 4),
       ('Karagandy', 4),
       ('Los Angeles', 5),
       ('New York City', 5),
       ('Chicago', 5),
       ('London', 6),
       ('Leeds', 6),
       ('Birmingham', 6),
       ('Rome', 7),
       ('Milan', 7),
       ('Naples', 7),
       ('Berlin', 8),
       ('Hamburg', 8),
       ('Munich', 8),
       ('Prague', 9),
       ('Brno', 9),
       ('Ostrava', 9),
       ('Madrid', 10),
       ('Barcelona', 10),
       ('Valencia', 10),
       ('Lisbon', 11),
       ('Porto', 11),
       ('Amadora', 11),
       ('Yerevan', 12),
       ('Gyumri', 12),
       ('Vanadzor', 12),
       ('Baku', 13),
       ('Sumqayit', 13),
       ('Ganja', 13),
       ('Copenhagen', 14),
       ('Aarhus', 14),
       ('Odense', 14),
       ('Oslo', 15),
       ('Bergen', 15),
       ('Trondheim', 15),
       ('Helsinki', 16),
       ('Espoo', 16),
       ('Tampere', 16),
       ('Istanbul', 17),
       ('Ankara', 17),
       ('Bursa', 17),
       ('Cairo', 18),
       ('Alexandria', 18),
       ('Giza', 18),
       ('Mumbai', 19),
       ('Delhi', 19),
       ('Bangalore', 19),
       ('Shanghai', 20),
       ('Beijing', 20),
       ('Chongqing', 20),
       ('Zurich', 21),
       ('Geneva', 21),
       ('Basel', 21),
       ('Tokyo', 22),
       ('Yokohama', 22),
       ('Osaka', 22),
       ('São Paulo', 23),
       ('Rio de Janeiro', 23),
       ('Brasilia', 23),
       ('Mexico City', 24),
       ('Ecatepec', 24),
       ('Guadalajara', 24),
       ('Vancouver', 25),
       ('Calgary', 25),
       ('Edmonton', 25),
       ('Seoul', 26),
       ('Busan', 26),
       ('Incheon', 26),
       ('Amsterdam', 27),
       ('Rotterdam', 27),
       ('The Hague', 27),
       ('Stockholm', 28),
       ('Gothenburg', 28),
       ('Malmo', 28),
       ('Jerusalem', 29),
       ('Tel Aviv-Yafo', 29),
       ('Haifa', 29),
       ('Warsaw', 30),
       ('Krakow', 30),
       ('Lodz', 30)
;